### ISSUE TITLE
[Epic] Relaunch

### ISSUE THREAD

**Issue by ashes999** [ashes999/rpg-maker-resource-index#19]
- [x] Replace VXA repo with this one
- [x] Directory structure: `resources/vxa/*`
- [x] Replace repositories with real JSON (setup instructions mention HTTP server)
- [x] Combine all JS files (app, controllers, etc.) into one
- [x] Get rid of that horrible grid.
- [x] Resources: add a type (tileset, sprite, battler, etc.)
- [x] Remove licensing information.
- [x] MV integration.
- [ ] Import old stuff
- [ ] Switch to Angular 2.0
- [ ] Clean up old issues
